### ISSUE TITLE
return more than just url?

### ISSUE THREAD

**Issue by jaequery** [thibauts/node-google-search-scraper#1]
it'd been real nice if it returned more than just the url, like title/description/date. is that even possible?

**Comment by teckays** [comment]
Would be nice to have the total number of results per specific query as well.

**Comment by thibauts** [comment]
In my opinion the number of search results, being an approximation and having no relation to actually retrievable results, doesn't add much value. But i guess is could be easily extracted and output on stderr, so as not to clobber the results output.

**Comment by perryjm** [comment]
Personally, would really benefit from this feature being in place! Thanks mnazwan for opening the enhancement!

**Comment by thibauts** [comment]
Merged and published to npm.

**Comment by perryjm** [comment]
Works great, thanks so much!
