### ISSUE TITLE
Error: getaddrinfo ENOTFOUND www.google.com

### ISSUE THREAD

**Issue by essaji** [thibauts/node-google-search-scraper#2]
I am getting this error while trying to execute on node

        if(error) throw error;
                        ^
       Error: getaddrinfo ENOTFOUND www.google.com
       at errnoException (dns.js:44:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

here is my piece of code 

    var scraper = require('./node_modules/google-search-scraper');
    var options = {
	query: 'Nodejs',
	limit: 10
    }
    scraper.search(options, function(error,url){
	if(error) throw error;
	console.log(url);
    });

**Comment by thibauts** [comment]
Looks like your local DNS client can't resolve google ;)

**Comment by essaji** [comment]
why not? is there any solution? by the way I am behind a proxy which I have already set in environment variables. Do I need to set proxy somewhere else as well? I appreciate your help.
